#!/bin/bash
# 2016-11-30 by dhd version 1.1
# OS : el6 x86_64
# For: yum ntp base_set update
# Note : DNS
# color machine run vmware tools ：vmware-config-tools.pl
###########################################################################

#set -o nounset

. /etc/rc.d/init.d/functions

# 定义变量
RED_COLOR='\E[1;31m'   	#红
GREEN_COLOR='\E[1;32m' 	#绿
YELOW_COLOR='\E[1;33m' 	#黄
BLUE_COLOR='\E[1;34m'  	#蓝
PINK='\E[1;35m'       	#粉红
RES='\E[0m'
GW="www.hao123.com"
NAME=`hostname`
FILE="/etc/yum.repos.d"
YUM="epel-release remi-release rpmforge-release rpmfusion-free-release"
DONE="\e[0;32m\032 OK \e[m"
ERRO="\e[0;31m\031 NO \e[m"

# 查看脚本说明
testFun(){
    head `pwd`/$0
    echo -e "${RED_COLOR} 此主机为：$NAME ${RES}"
    echo -e "${RED_COLOR} -------------------------------- ${RES}"
}

check_Fun(){
    [ $? -eq 0 ] && echo -e "${DONE}" || echo -e "${ERRO}"
}

base_Fun(){

# 关闭防火墙
chkconfig iptables off
sed -i s/SELINUX=enforcing/SELINUX=disabled/  /etc/selinux/config
setenforce 0
	
# 网卡设置
cp /etc/udev/rules.d/70-persistent-net.rules{,.bak}
> /etc/udev/rules.d/70-persistent-net.rules

# 基础安装
yum install lsof vim tree screen tree lrzss wget net-tools \
ntp openssl openssl-devel kernel-devel-$(uname -r) -y

# DNS
cat >/etc/resolv.conf<<EOF
Generated by NetworkManager
ameserver 192.168.188.254
ameserver 211.167.230.100
#nameserver 211.167.230.200
EOF

# 时间同步
cp /etc/localtime{,.bak}
ln -sf /usr/share/zoneinfo/posix/Asia/Shanghai /etc/localtime
ntpdate 0.cn.pool.ntp.org
cat >>/etc/ntp.conf<<EOF
server 0.cn.pool.ntp.org
server 1.cn.pool.net.org
server 2.cn.pool.net.org
EOF

/etc/init.d/ntpd start
chkconfig --level 35 ntpd on

# 关闭服务
#chkconfig --list | grep 3:on
chkconfig ip6tables off

}

# 安装
installFun(){
# 检测网络
    ping -c1 $GW &> /dev/null
    [ $? -ne 0 ] && echo -e "${RED_COLOR} 检查你的网络 ${RES}" && exit

# 安装第三方源
    # 163
    wget -P $FILE/ http://mirrors.163.com/.help/CentOS6-Base-163.repo
    mv $FILE/CentOS-Base.repo{,.bak}
		
	# epel
    rpm -ivh http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm 1> /dev/null
    #rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6 1> /dev/null
	
	# remi	
    rpm -ivh http://rpms.famillecollet.com/enterprise/remi-release-6.rpm 1> /dev/null
	#rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-remi 1> /dev/null
	
	# rpmforge-release
	# 地址不好找
	rpm -ivh http://ftp.tu-chemnitz.de/pub/linux/dag/redhat/el6/en/x86_64/rpmforge/RPMS/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm

	# rpmfusion-free-release
	rpm -ivh http://download1.rpmfusion.org/free/el/updates/6/x86_64/rpmfusion-free-release-6-1.noarch.rpm
	
	# atomic
    #wget -P /tmp http://www.atomicorp.com/installers/atomic &> /dev/null
    #sh /tmp/atomic		
	
# 重建缓存
    echo -e "${GREEN_COLOR} 请等待建立缓存...... ${RES}"
    yum makecache
    [ $? -eq 0 ] && echo -e "${GREEN_COLOR} 缓存成功 ${RES}"
	
# 升级
    echo -e "${GREEN_COLOR} 请等待升级...... ${RES}"
    yum install axel git yum-fastestmirror -y
    cd /tmp
    git clone https://github.com/crook/yum-axelget &> /dev/null
	cp /etc/yum/pluginconf.d/axelget.conf{,.bak}
	cp /usr/lib/yum-plugins/axelget.py{,.bak}
    cp yum-axelget/axelget.conf /etc/yum/pluginconf.d/
    cp yum-axelget/axelget.py /usr/lib/yum-plugins/
	
	rpm -qa | grep axel
	ls /usr/bin/axel
	
    yum update -y
    [ $? -eq 0 ] && echo -e "${GREEN_COLOR} 升级成功 ${RES}"

}

# 交互输入
testFun
read -p "确定执行吗 [y/n]？" RE
case $RE in
    y | Y)
        echo -e "${RED_COLOR} 请等待...... ${RES}"
	    yum groupinstall 'Development Tools' -y
	    yum groupinstall Base -y
	    base_Fun
	    installFun
	    ;;
    n | N)
	    exit
	    ;;
    *)
	    echo -e "${RED_COLOR} 错误 ${RES}"
	    exit
esac