#!/bin/bash
# 2016-11-25 by dhd
# Note: VMwaretools

NAME="centos7.test.com"

# Install
yum install vim ntp screen lrzsz tree wget net-tools open-vm-tools ntp openssl openssl-devel kernel-devel-$(uname -r) -y
yum groupinstall "Development tools" -y
yum groupinstall Base -y

# SET eth0
mkdir /root/test
mv /etc/sysconfig/network-scripts/ifcfg-eno* /root/test

cat >/etc/sysconfig/network-scripts/ifcfg-eth0<<EOF
TYPE="Ethernet"
DEVICE="eth0"
ONBOOT="yes"
BOOTPROTO="dhcp"

#BOOTPROTO="none"
#IPADDR=192.168.189.42
#GATEWAY=192.168.189.1
#NETMASK=255.255.255.0

#DEFROUTE="yes"
#PEERDNS="yes"
#PEERROUTES="yes"
#IPV4_FAILURE_FATAL="no"
EOF

systemctl restart network.service

cp /etc/sysconfig/grub{,.bak}
cat >/etc/sysconfig/grub<<EOF
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap net.ifnames=0 biosdevname=0 rhgb quiet"
GRUB_DISABLE_RECOVERY="true"
EOF

grub2-mkconfig -o /boot/grub2/grub.cfg

# IPV6
echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf

# SET bashrc

# SET hostname
hostnamectl set-hostname $NAME 

# SET time
ln -sf /usr/share/zoneinfo/posix/Asia/Shanghai /etc/localtime
ntpdate -u cn.pool.ntp.org
#ntpdate 0.cn.pool.ntp.org
cat >>/etc/ntp.conf<<EOF
server 0.cn.pool.ntp.org
server 1.cn.pool.net.org
server 2.cn.pool.ntp.org
EOF

systemctl enable ntpd
systemctl restart ntpd

# SET dns
cat >/etc/resolv.conf<<EOF
# Generated by NetworkManager
nameserver 192.168.188.254
nameserver 211.167.230.100
nameserver 211.167.230.200
EOF

# STOP firewalld
systemctl stop firewalld.service
systemctl disable firewalld.service

# EPEL REMI
yum install epel-release -y
rpm -ivh http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

# ssh
#mkdir ~/.ssh/
#chmod 700 ~/.ssh
#echo "" > ~/.ssh/authorized_keys
#chmod 600 ~/.ssh/authorized_keys

# UPdate
cat /etc/redhat-release 
#CentOS Linux release 7.2.1511 (Core)
yum update -y